---
# Instalación de cloudflared 
- name: Creación de directorio para llave gpg
  command: mkdir -p --mode=0755 /usr/share/keyrings
  become: yes

- name: Se agrega llave gpg
  shell: curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  become: yes

- name: Se agrega el repositorio de cloudflare en apt
  shell: echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared buster main' | tee /etc/apt/sources.list.d/cloudflared.list
  become: yes

- name: instalación de cloudflared
  apt:
    update_cache: yes
    name: cloudflared


# Configuración de cloudflared #
- name: Creación del directorio .cloudflared
  file:
    path: /root/.cloudflared
    state: directory
    owner: root
    group: root

- name: Se copia archivo json en el directorio /root/.cloudflared
  copy:
    src: 130f9c3a-3bd7-4294-927b-c9f8e44aebc3.json
    dest: /root/.cloudflared/130f9c3a-3bd7-4294-927b-c9f8e44aebc3.json
    decrypt: yes
    owner: root
    group: root
    mode: 0644

- name: Copia del certificado cert.pem en el directorio /root/.cloudflared
  copy:
    src: cert.pem
    dest: /root/.cloudflared/cert.pem
    decrypt: yes
    owner: root
    group: root
    mode: 0600

- name: Copia de config.yml en el directorio /root/.cloudflared
  copy:
    src: config.yml
    dest: /root/.cloudflared/config.yml
    owner: root
    group: root
    mode: 0644

# Habilitación de cloudflared como servicio
- name: Creación del directorio /etc/cloudflared
  file:
    path: /etc/cloudflared
    state: directory
    owner: root
    group: root

- name: Mover archivo config.yml al directorio /etc/cloudflared
  command: cp /root/.cloudflared/config.yml /etc/cloudflared/
  become: yes

- name: Instalación de servicio cloudflared
  command: cloudflared --config /etc/cloudflared/config.yml service install
  become: yes

- name: Iniciar el servicio cloudflared
  command: systemctl start cloudflared
  become: yes

