---
# Instalación de openvscode-server
- name: Creación del directorio openvscode-server
  file:
    path: /home/<user>/openvscode-server
    state: directory
    owner: <user>
    group: <user>

- name: Descargar openvscode-server
  ansible.builtin.get_url:
    url: https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.71.2/openvscode-server-v1.71.2-linux-x64.tar.gz
    dest: /home/<user>/openvscode-server/openvscode-server-v1.71.2-linux-x64.tar.gz
    mode: '0640'

- name: Extraer archivo tar.gz en el directorio /root/openvscode-server
  ansible.builtin.unarchive:
    src: /home/<user>/openvscode-server/openvscode-server-v1.71.2-linux-x64.tar.gz
    dest: /home/<user>/openvscode-server/
    remote_src: yes

- name: Agregar openvscode-server como servicio
  copy:
    src: openvscode-server.service
    dest: /etc/systemd/system/openvscode-server.service
    owner: root
    group: root
    mode: 0644

- name: Iniciar el servicio openvscode-server
  service:
    name: openvscode-server
    state: started