---
# Instalación de paquetes base
- name: Instalación de paquetes base
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - gnupg
    - software-properties-common
    - ca-certificates
    - curl
    - apt-transport-https
    - ansible
    - wireguard
    - resolvconf

# Instalación de MOSH shell
- name: Instación de aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Instalación de MOSH shell
  apt:
    pkg:
      - mosh
    state: latest
    update_cache: true

# Instalación de Terraform
- name: Instalación de la llave gpg de Hashicorp
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: yes

- name: Verificando el fingerprint de la llave
  shell: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

- name: Se agrega el repositorio de Hashicorp
  shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  become: yes

- name: Instalación de Terraform
  apt:
    update_cache: yes
    name: terraform

# Instalación de Kubectl
- name: Instalación de la llave gpg de Google Cloud
  command: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: yes

- name: Se agrega el repositorio de Google Kubernetes
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
  become: yes

- name: Instalación de Kubectl
  apt:
    update_cache: yes
    name: kubectl

# Instalación de gcloud CLI
- name: Instalación del package distribution de gcloud
  shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  become: yes

- name: Instalación de la llave pgp de gcloud
  shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  become: yes

- name: Instalación de gcloud CLI
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - google-cloud-cli
    - google-cloud-sdk-gke-gcloud-auth-plugin

# Configuración de Wireguard
- name: copia del archivo de configuración de dominio a /etc/wireguard
  copy:
    src: domain.conf
    dest: /etc/wireguard/domain.conf
    decrypt: yes
    owner: root
    group: root
    mode: 0644

# Instalación de Docker
- name: Se agrega llave GPG de Docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  become: yes

- name: Se agrega repositorio de Docker
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  become: yes

- name: Se instala Docker y Docker Compose
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Se verifica que el grupo docker existe
  group:
    name: docker
    state: present

- name: Sea grega el usuario <user> al grupo docker
  user:
    name: <user>
    groups: docker
    append: yes

- name: Se activan cambios en el grupo docker
  command: newgrp docker

# Instalación de Kubectx
- name: Instalación de kubectx
  snap:
    name:
      - kubectx
    classic: yes

# Instalación de Kube-ps1
- name: copia del archivo .kube-ps1.sh al directorio /home/<user>
  copy:
    src: .kube-ps1.sh
    dest: /home/<user>/.kube-ps1.sh
    owner: <user>
    group: <user>
    mode: 0644


