---
# Configuración del hostname
- name: Configuración del hostname
  ansible.builtin.hostname:
    name: <hostname>

# Crea el usuario '<user>'
- name: Crea el usuario '<user>'
  user:
    name: <user>
    password: "{{ <user>_user_password | password_hash('sha512') }}"
    generate_ssh_key: yes
    append: yes
    groups: sudo
    state: present
    home: /home/<user>
    shell: /bin/bash

- name: Crea el archivo authorized_keys
  file:
    path: /home/<user>/.ssh/authorized_keys
    state: touch
    owner: <user>
    group: <user>
    mode: 0600

- name: Agrega la llave SSH pública al archivo authorized_keys
  lineinfile:
    path: /home/<user>/.ssh/authorized_keys
    state: present
    insertafter: EOF
    line: "{{ <user>_ssh_public_key }}"
    owner: <user>
    group: <user>
    mode: 0600

# SSH configurado para no aceptar password ni root
- name: Copia del archivo sshd_config al direcorio /etc/ssh/sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart SSH

# Copia del archivo .bashrc al directorio /home/<user>
- name: Copia de .bashrc al directorio /home/<user>
  copy:
    src: .bashrc
    dest: /home/<user>/.bashrc
    decrypt: yes
    owner: <user>
    group: <user>
    mode: 0644

# Configuración del firewall
- name: Enable UFW
  ufw:
    state: enabled

- name: Allow access to ssh port
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow access to webserver
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - '80'
    - '443'

- name: Allow access to mosh ports
  ufw:
    rule: allow
    port: '60001:60999'
    proto: udp

- name: Allow access to wireguard port
  ufw:
    rule: allow
    port: '51820'
    proto: udp
