tunnel: <cloudflare_tunnel_id>
credentials-file: /root/.cloudflared/<cloudflare_tunnel_id>.json

ingress:
  - hostname: <vscode.domain.com>
    service: http://localhost:8080
  - hostname: <ssh.domain.com>
    service: ssh://localhost:22
  - service: http_status:404