---
- hosts: all
  become: true
  roles:
    - base
  vars:
    rubiops_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5VSnbslYFWFaE0hL62UssKbDWuugjv2ui/uBgFuVXsu3Fz9JHi7hgKkCPGyibhkVpYp/ZJBe6rKh7VB1vHY3nzKHOT2LO7uAYdwFGn8Mq1vLLBm8NVspNH0wmP/aNRAqzUQEPsT63PYA7InAdIZipYmwx968j67qnicKr98ZUG+XcZbCPd8gLNwwBYNZMPFoRb4AnBvuarnTBobdNnDUwFu6b7vJ6Lhds1tTbeBJJl3sKNe6QVPFtTELth/C2dfoHbOvMB77bBOc00Pc1SZo4OASMrTIvkzxzNhSQCqa/TxpA10m9UT8mdi//ZbD5HrLVO1+HbC2h4IamO4IpRa25 oscar@rubiops.tech
