---
# !!!!!!!!!!!!!!!!! Docker installation !!!!!!!!!!!!
####################################################

- name: Docker dependency packages   
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Adding Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Adding Docker repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Permisos para docker-compose
  file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: '0744'

# !!!!!!!!!!!!!!! SSH setup !!!!!!!!!!!!!!!!!!!!!!!
# Docker-compose for wireguard service
- name: copy docker-compose to /root directory
  copy:
    src: docker-compose.yml
    dest: /root/docker-compose.yml
    owner: root
    group: root
    mode: 0644

# !!!!!! UFW setup !!!!!!!!!!!!!!
- name: Allow everything and enable UFW
  ufw:
    state: enabled

- name: Allow all access to ssh port
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow all access to wireguard
  ufw:
    rule: allow
    port: 51820
    proto: udp




